#!/usr/bin/env php
<?php

// Load the composer autoloader
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$app = new \Symfony\Component\Console\Application('Athenaeum', '1.x.x');
$app->run();
