#!/usr/bin/env php
<?php

/*****************************************************************
 * Autoloader
 ****************************************************************/

// Load the composer autoloader
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

/*****************************************************************
 * Imports
 ****************************************************************/

use Jean85\PrettyVersions;

/*****************************************************************
 * Create & Run Application
 ****************************************************************/

$version = PrettyVersions::getVersion('aedart/athenaeum');

$app = new \Symfony\Component\Console\Application('Athenaeum', $version->getPrettyVersion());
$app->run();
